feat(config): add commit msg

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,7 +12,7 @@ npx lint-staged ||
 )
 
 # Check Prettier standards
-npm run format ||
+npm run format:dev ||
 (
     echo '\n❌⭕❌⭕ Prettier Format Failed ❌⭕❌⭕
     Run npm run format, add changes and try commit again.';
@@ -20,13 +20,24 @@ npm run format ||
 )
 
 # Check ESLint Standards
-npm run check-format ||
+npm run check-format:dev ||
 (
     echo '\n 😤🏀👋😤 Prettier Check Failed 😤🏀👋😤
     Make the required changes listed above, add changes and try to commit again.'
     false;
 )
-
+npm run format:prod ||
+(
+    echo '\n 😤🏀👋😤 Prettier Check Failed 😤🏀👋😤
+    Make the required changes listed above, add changes and try to commit again.'
+    false;
+)
+  npm run check-format:prod ||
+(
+    echo '\n 😤🏀👋😤 Prettier Check Failed 😤🏀👋😤
+    Make the required changes listed above, add changes and try to commit again.'
+    false;
+)
 # If everything passes... Now we can build
 echo '\n 🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
 
@@ -38,4 +49,4 @@ npm run build ||
 )
 
 # If everything passes... Now we can commit
-echo '✅✅✅✅ Amazing !! I am committing this now. ✅✅✅✅'
+echo '✅ ✅ ✅ ✅ Amazing !! I am committing this now. ✅ ✅ ✅ ✅'
